import type { Movie, TVShow, Season, Episode, Genre } from "./types"

export const mockMovies: Movie[] = [
  {
    id: "1",
    tmdb_id: 550,
    title: "Fight Club",
    overview:
      "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.",
    poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop_path: "/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg",
    release_date: "1999-10-15",
    runtime: 139,
    vote_average: 8.4,
    vote_count: 26280,
    genres: [{ id: "1", tmdb_id: 18, name: "Drama", created_at: "" }],
    embed_url: "https://example.com/embed/fight-club",
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    tmdb_id: 13,
    title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events.",
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop_path: "/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    release_date: "1994-06-23",
    runtime: 142,
    vote_average: 8.5,
    vote_count: 25000,
    genres: [
      { id: "1", tmdb_id: 18, name: "Drama", created_at: "" },
      { id: "2", tmdb_id: 35, name: "Comedy", created_at: "" },
    ],
    embed_url: "https://example.com/embed/forrest-gump",
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    tmdb_id: 238,
    title: "The Shawshank Redemption",
    overview:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    backdrop_path: "/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg",
    release_date: "1994-09-23",
    runtime: 142,
    vote_average: 9.3,
    vote_count: 24000,
    genres: [{ id: "1", tmdb_id: 18, name: "Drama", created_at: "" }],
    embed_url: "https://example.com/embed/shawshank",
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    tmdb_id: 155,
    title: "The Dark Knight",
    overview:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/hqkIcbrOHL86UncnHIsHVcVmzue.jpg",
    release_date: "2008-07-18",
    runtime: 152,
    vote_average: 9.0,
    vote_count: 28000,
    genres: [
      { id: "3", tmdb_id: 28, name: "Action", created_at: "" },
      { id: "4", tmdb_id: 80, name: "Crime", created_at: "" },
    ],
    embed_url: "https://example.com/embed/dark-knight",
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    tmdb_id: 680,
    title: "Pulp Fiction",
    overview:
      "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop_path: "/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg",
    release_date: "1994-09-10",
    runtime: 154,
    vote_average: 8.9,
    vote_count: 26500,
    genres: [
      { id: "4", tmdb_id: 80, name: "Crime", created_at: "" },
      { id: "1", tmdb_id: 18, name: "Drama", created_at: "" },
    ],
    embed_url: "https://example.com/embed/pulp-fiction",
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "6",
    tmdb_id: 424,
    title: "Schindler's List",
    overview:
      "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    release_date: "1993-12-15",
    runtime: 195,
    vote_average: 9.0,
    vote_count: 13500,
    genres: [
      { id: "1", tmdb_id: 18, name: "Drama", created_at: "" },
      { id: "5", tmdb_id: 36, name: "History", created_at: "" },
    ],
    embed_url: "https://example.com/embed/schindlers-list",
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
]

export const mockTVShows: TVShow[] = [
  {
    id: "1",
    tmdb_id: 1399,
    name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    first_air_date: "2011-04-17",
    last_air_date: "2019-05-19",
    number_of_seasons: 8,
    number_of_episodes: 73,
    vote_average: 9.2,
    vote_count: 21000,
    genres: [
      { id: "6", tmdb_id: 10765, name: "Sci-Fi & Fantasy", created_at: "" },
      { id: "1", tmdb_id: 18, name: "Drama", created_at: "" },
    ],
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    tmdb_id: 1396,
    name: "Breaking Bad",
    overview:
      "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    first_air_date: "2008-01-20",
    last_air_date: "2013-09-29",
    number_of_seasons: 5,
    number_of_episodes: 62,
    vote_average: 9.5,
    vote_count: 19000,
    genres: [
      { id: "1", tmdb_id: 18, name: "Drama", created_at: "" },
      { id: "4", tmdb_id: 80, name: "Crime", created_at: "" },
    ],
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    tmdb_id: 60735,
    name: "The Flash",
    overview:
      "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma.",
    poster_path: "/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg",
    backdrop_path: "/9Jmd1OumCjaXDkpllbSGi2EpJvl.jpg",
    first_air_date: "2014-10-07",
    last_air_date: "2023-05-24",
    number_of_seasons: 9,
    number_of_episodes: 184,
    vote_average: 7.7,
    vote_count: 9500,
    genres: [
      { id: "6", tmdb_id: 10765, name: "Sci-Fi & Fantasy", created_at: "" },
      { id: "1", tmdb_id: 18, name: "Drama", created_at: "" },
    ],
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    tmdb_id: 1402,
    name: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies.",
    poster_path: "/rqeYMLryjcawh2JeRpCVUDXYM5b.jpg",
    backdrop_path: "/uro2Khv7JxlzXtLb8tCIbRhkb9E.jpg",
    first_air_date: "2010-10-31",
    last_air_date: "2022-11-20",
    number_of_seasons: 11,
    number_of_episodes: 177,
    vote_average: 8.1,
    vote_count: 14000,
    genres: [
      { id: "7", tmdb_id: 27, name: "Horror", created_at: "" },
      { id: "1", tmdb_id: 18, name: "Drama", created_at: "" },
    ],
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    tmdb_id: 1418,
    name: "The Big Bang Theory",
    overview:
      "A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life.",
    poster_path: "/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
    backdrop_path: "/nGsNruW3W27V6r4gkyc3iiEGsKR.jpg",
    first_air_date: "2007-09-24",
    last_air_date: "2019-05-16",
    number_of_seasons: 12,
    number_of_episodes: 279,
    vote_average: 8.2,
    vote_count: 11000,
    genres: [{ id: "2", tmdb_id: 35, name: "Comedy", created_at: "" }],
    status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
]

export const mockSeasons: Season[] = [
  {
    id: "1",
    tv_show_id: "1", // Game of Thrones
    tmdb_id: 3624,
    season_number: 1,
    name: "Season 1",
    overview: "Trouble is brewing in the Seven Kingdoms of Westeros.",
    poster_path: "/zwaj4egrhnXOBIit1tyb4Sbt3KP.jpg",
    air_date: "2011-04-17",
    episode_count: 10,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    tv_show_id: "2", // Breaking Bad
    tmdb_id: 3572,
    season_number: 1,
    name: "Season 1",
    overview: "High school chemistry teacher Walter White's life is suddenly transformed.",
    poster_path: "/1BP4xYv9ZG4ZVHkL7ocOziBbSYH.jpg",
    air_date: "2008-01-20",
    episode_count: 7,
    created_at: "2024-01-01T00:00:00Z",
  },
]

export const mockEpisodes: Episode[] = [
  {
    id: "1",
    season_id: "1",
    tv_show_id: "1",
    tmdb_id: 63056,
    episode_number: 1,
    season_number: 1,
    name: "Winter Is Coming",
    overview:
      "Eddard Stark is torn between his family and an old friend when asked to serve at the side of King Robert Baratheon.",
    still_path: "/9sjxtgLZsRYd2yp9RgthXzqbNgF.jpg",
    air_date: "2011-04-17",
    runtime: 62,
    vote_average: 9.0,
    vote_count: 111,
    embed_url: "https://example.com/embed/got-s1e1",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    season_id: "2",
    tv_show_id: "2",
    tmdb_id: 62085,
    episode_number: 1,
    season_number: 1,
    name: "Pilot",
    overview: "Walter White, a struggling high school chemistry teacher, is diagnosed with inoperable lung cancer.",
    still_path: "/ydlY3iPfeOAvu8gVqrxPoMvzNCn.jpg",
    air_date: "2008-01-20",
    runtime: 58,
    vote_average: 8.2,
    vote_count: 117,
    embed_url: "https://example.com/embed/bb-s1e1",
    created_at: "2024-01-01T00:00:00Z",
  },
]

export const mockGenres: Genre[] = [
  { id: "1", tmdb_id: 18, name: "Drama", created_at: "2024-01-01T00:00:00Z" },
  { id: "2", tmdb_id: 35, name: "Comedy", created_at: "2024-01-01T00:00:00Z" },
  { id: "3", tmdb_id: 28, name: "Action", created_at: "2024-01-01T00:00:00Z" },
  { id: "4", tmdb_id: 80, name: "Crime", created_at: "2024-01-01T00:00:00Z" },
  { id: "5", tmdb_id: 36, name: "History", created_at: "2024-01-01T00:00:00Z" },
  { id: "6", tmdb_id: 10765, name: "Sci-Fi & Fantasy", created_at: "2024-01-01T00:00:00Z" },
  { id: "7", tmdb_id: 27, name: "Horror", created_at: "2024-01-01T00:00:00Z" },
]
